# Generated by Django 2.2.7 on 2019-12-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_submission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
    ]
